# Fonts
font_family JetBrainsMono Nerd Font
font_size 14
disable_ligatures never
bold_font auto
italic_font auto
bold_italic_font auto
editor /opt/homebrew/bin/nvim

# Appearances
adjust_line_height 130%

# Tab settings
tab_bar_style powerline
tab_bar_style fade
tab_fade 1
active_tab_foreground   #3d59a1
active_tab_background   #16161e
active_tab_font_style   bold
inactive_tab_foreground #787c99
inactive_tab_background #16161e
inactive_tab_font_style bold
tab_bar_background #101014

# Windows settings
window_resize_step_cells 2
window_resize_step_lines 2
initial_window_width 800
initial_window_height 600

# Colorscheme
foreground #a9b1d6
background #1a1b26
color0 #414868
color8 #414868
color1 #f7768e
color9 #f7768e
color2  #73daca
color10 #73daca
color3  #e0af68
color11 #e0af68
color4  #7aa2f7
color12 #7aa2f7
color5  #bb9af7
color13 #bb9af7
color6  #7dcfff
color14 #7dcfff
cursor #c0caf5
cursor_text_color #1a1b26
selection_foreground none
selection_background #28344a
url_color #9ece6a
active_border_color #3d59a1
inactive_border_color #101014
bell_border_color #e0af68

# Fix <A> key not working in macOS
macos_option_as_alt yes

# Mapping

# New tab
map cmd+t new_tab_with_cwd

# clear the terminal screen
map cmd+k combine : clear_terminal scrollback active : send_text normal,application \x0c
map cmd+f launch --type=overlay --stdin-source=@screen_scrollback /opt/homebrew/bin/fzf --no-sort --no-mouse --exact -i

# jump to beginning and end of word
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

# jump to beginning and end of line
map cmd+left send_text all \x01
map cmd+right send_text all \x05

# Map cmd + <num> to corresponding tabs
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# changing font sizes
map cmd+equal change_font_size all +2.0
map cmd+minus change_font_size all -2.0
map cmd+0 change_font_size all 0

map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map cmd+w close_window
map cmd+shif+n new_os_window
map cmd+d launch --location=hsplit --cwd=current
map cmd+shift+d launch --location=vsplit --cwd=current

# Rotate the current split, chaging its split axis from vertical to horizontal or vice versa
map ctrl+shift+r layout_action rotate

# Switch focus to the neighboring window in the indicated direction
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down

# Switch tabs
map cmd+] next_tab
map cmd+[ previous_tab
map ctrl+cmd+l next_tab
map ctrl+cmd+h previous_tab

enabled_layouts splits:split_axis=horizontal

