
[bell]
animation = "EaseOutExpo"
duration = 0

[env]
TERM = "xterm-256color"

[font]
size = 13

[terminal.shell]
program = "/bin/zsh"

[font.bold]
family = "JetBrainsMono Nerd Font"
#family = "OperatorMonoSSmLig Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Full"
opacity = 0.8
blur = true
dynamic_title = false
startup_mode = "Windowed"
option_as_alt = "Both"
padding = { x = 12, y = 0 }
decorations_theme_variant = "Dark"

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/themes/tokyo_night.toml"
  #"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[terminal]
